"""Unit tests for torch.compile operations in WAN 2.2 S2V model.

This file contains tests for Triton JIT kernels and CompiledFxGraph operations
generated by torch.compile during inference.

## Test Classes

1. **TestTritonJITKernels** (7 tests)
   - Tests auto-generated Triton kernels from torch.inductor
   - Total overhead: ~453.30ms

2. **TestCompiledFxGraphOps** (12 tests)
   - Tests CompiledFxGraph instances (FX graph representations)
   - Total overhead: ~137.18ms
   - Includes self-attention, cross-attention, and segment modulation tests

## Running Tests

```bash
# Run all torch.compile tests
pytest test_wan22_torch_compile.py -v -s

# Run Triton kernel tests only
pytest test_wan22_torch_compile.py::TestTritonJITKernels -v -s

# Run CompiledFxGraph tests only
pytest test_wan22_torch_compile.py::TestCompiledFxGraphOps -v -s
```

## Benchmark Modes

The test suite supports two modes:

**Benchmark Mode (default):**
- `BENCHMARK_MODE=1` or not set
- Performs 1 warmup run + 1 benchmark run
- Faster than baseline tests while still measuring warmed-up performance
- Optimized for torch.compile overhead measurements

**Fast Mode:**
- `BENCHMARK_MODE=0`
- Single run, no warmup
- Faster execution for quick validation
- Results include cold-start overhead

Example:
```bash
# Fast mode: No warmup, single run (includes cold-start overhead)
BENCHMARK_MODE=0 pytest test_wan22_torch_compile.py::TestTritonJITKernels -v -s

# Benchmark mode (default): 1 warmup + 1 run (warmed-up performance)
pytest test_wan22_torch_compile.py::TestTritonJITKernels -v -s
```

Usage:
```bash
# Run all tests with benchmarking (default: 1 warmup + 1 run)
pytest test_wan22_torch_compile.py -v -s

# Run in fast mode (no warmup, includes compilation overhead)
BENCHMARK_MODE=0 pytest test_wan22_torch_compile.py -v -s
```

## Related Documentation

- TRITON_KERNEL_MAPPING.md - Triton kernel analysis
- COMPILED_FX_GRAPH_MAPPING.md - CompiledFxGraph analysis
- COMPILED_FX_GRAPH_TESTS.md - Detailed test descriptions
- wan22_torch_compile_test_report.md - Auto-generated test report
"""

import os

import numpy as np
import pytest
import torch

# Test device configuration
DEVICE = "xpu" if torch.xpu.is_available() else "cpu"

# Configuration from profiling runs (WAN 2.2 A14B)
BATCH_SIZE = 1
SEQ_LEN = 75600  # 21 × 45 × 80 patches
HIDDEN_DIM = 5120
NUM_HEADS = 40
HEAD_DIM = 128
FFN_DIM = 13824
TEXT_SEQ_LEN = 512
NUM_FRAMES_T2V = 81
NUM_FRAMES_S2V = 80
LATENT_HEIGHT = 90
LATENT_WIDTH = 160

WARMUP = 1
RUNS = 1

# Benchmark mode: if False, run only once (no warmup, no averaging)
# Set via environment variable: BENCHMARK_MODE=0 to disable
# Default: 1 (enabled) for accurate torch.compile overhead measurements
BENCHMARK_MODE = os.environ.get("BENCHMARK_MODE", "1") != "0"

# Store test results for report generation
TEST_RESULTS = []


def calculate_flops(op_type, shape_info):
    """Calculate FLOPs for different operation types."""
    if op_type == "conv1d":
        batch = shape_info["batch"]
        in_ch = shape_info["in_channels"]
        out_ch = shape_info["out_channels"]
        kernel = shape_info["kernel_size"]
        out_len = shape_info["output_length"]
        return 2 * batch * out_ch * out_len * in_ch * kernel

    elif op_type == "conv2d":
        batch = shape_info["batch"]
        in_ch = shape_info["in_channels"]
        out_ch = shape_info["out_channels"]
        k_h = shape_info["kernel_h"]
        k_w = shape_info["kernel_w"]
        out_h = shape_info["output_h"]
        out_w = shape_info["output_w"]
        return 2 * batch * out_ch * out_h * out_w * in_ch * k_h * k_w

    elif op_type == "conv3d":
        batch = shape_info["batch"]
        in_ch = shape_info["in_channels"]
        out_ch = shape_info["out_channels"]
        k_d = shape_info["kernel_d"]
        k_h = shape_info["kernel_h"]
        k_w = shape_info["kernel_w"]
        out_d = shape_info["output_d"]
        out_h = shape_info["output_h"]
        out_w = shape_info["output_w"]
        return 2 * batch * out_ch * out_d * out_h * out_w * in_ch * k_d * k_h * k_w

    elif op_type == "linear":
        batch = shape_info["batch"]
        seq_len = shape_info["seq_len"]
        in_features = shape_info["in_features"]
        out_features = shape_info["out_features"]
        return 2 * batch * seq_len * in_features * out_features

    elif op_type == "flash_attn":
        batch = shape_info["batch"]
        num_heads = shape_info["num_heads"]
        seq_len = shape_info["seq_len"]
        head_dim = shape_info["head_dim"]
        return 4 * batch * num_heads * seq_len * seq_len * head_dim

    elif op_type == "elementwise":
        return shape_info.get("elements", 0) * 2  # Minimal compute

    else:
        return 0


def calculate_memory_bytes(op_type, shape_info):
    """Calculate total memory bytes accessed."""
    dtype_bytes = 2  # bfloat16 = 2 bytes

    if op_type in ["conv1d", "conv2d", "conv3d"]:
        input_bytes = shape_info["input_size"] * dtype_bytes
        weight_bytes = shape_info["weight_size"] * dtype_bytes
        output_bytes = shape_info["output_size"] * dtype_bytes
        return input_bytes + weight_bytes + output_bytes

    elif op_type == "linear":
        batch = shape_info["batch"]
        seq_len = shape_info["seq_len"]
        in_features = shape_info["in_features"]
        out_features = shape_info["out_features"]
        input_bytes = batch * seq_len * in_features * dtype_bytes
        weight_bytes = in_features * out_features * dtype_bytes
        output_bytes = batch * seq_len * out_features * dtype_bytes
        return input_bytes + weight_bytes + output_bytes

    elif op_type == "flash_attn":
        batch = shape_info["batch"]
        num_heads = shape_info["num_heads"]
        seq_len = shape_info["seq_len"]
        head_dim = shape_info["head_dim"]
        # Q, K, V inputs + output
        return 4 * batch * num_heads * seq_len * head_dim * dtype_bytes

    elif op_type == "elementwise":
        return shape_info.get("elements", 0) * dtype_bytes * 2  # Read + write

    else:
        return 0


def benchmark_with_metrics(name, prepare_fn, compute_fn, op_type, shape_info, profiling_info=None, benchmark=None):
    """
    Benchmark with CPU→XPU workflow, measuring kernel time only.

    Args:
        name: Test name
        prepare_fn: Function that creates tensors/models on CPU, returns (tensors_dict, operation)
        compute_fn: Function that performs computation, takes (tensors_dict, operation)
        op_type: Operation type for FLOP calculation
        shape_info: Shape information for metrics
        profiling_info: Optional profiling notes
        benchmark: If True, do warmup + 5 runs. If False, run once only. If None, use BENCHMARK_MODE.

    Returns:
        Dict with metrics or None if CPU
    """
    if DEVICE == "cpu":
        return None

    # Use global BENCHMARK_MODE if not explicitly specified
    benchmark = BENCHMARK_MODE

    # Step 1: Prepare on CPU
    tensors_dict, operation = prepare_fn()

    # Step 2: Transfer to XPU (not measured)
    tensors_xpu = {}
    for k, v in tensors_dict.items():
        if isinstance(v, torch.Tensor):
            tensors_xpu[k] = v.to("xpu")
        else:
            tensors_xpu[k] = v

    # Transfer operation(s) to XPU
    if operation is None:
        pass  # No operation to transfer
    elif isinstance(operation, (tuple, list)):
        # Handle multiple operations (e.g., k_proj, v_proj)
        operation = type(operation)(op.to("xpu") if hasattr(op, "to") else op for op in operation)
    elif hasattr(operation, "to"):
        operation = operation.to("xpu")

    # Step 3: Warmup (if benchmark mode)
    if benchmark:
        for _ in range(WARMUP):
            compute_fn(tensors_xpu, operation)
            torch.xpu.synchronize()

    # Step 4: Benchmark kernel only
    latencies = []
    num_runs = RUNS if benchmark else 1
    for _ in range(num_runs):
        torch.xpu.synchronize()
        start = torch.xpu.Event(enable_timing=True)
        end = torch.xpu.Event(enable_timing=True)

        start.record()
        compute_fn(tensors_xpu, operation)
        end.record()

        torch.xpu.synchronize()
        latencies.append(start.elapsed_time(end))

    # Step 5: Calculate metrics
    avg_ms = np.mean(latencies)
    std_ms = np.std(latencies)

    total_flops = calculate_flops(op_type, shape_info)
    total_memory_bytes = calculate_memory_bytes(op_type, shape_info)

    tflops = (total_flops / (avg_ms / 1000)) / 1e12 if avg_ms > 0 else 0
    memory_bw_gbs = (total_memory_bytes / (avg_ms / 1000)) / 1e9 if avg_ms > 0 else 0

    result = {
        "name": name,
        "avg_ms": avg_ms,
        "std_ms": std_ms,
        "tflops": tflops,
        "memory_bw_gbs": memory_bw_gbs,
        "shape_info": shape_info,
        "profiling_info": profiling_info,
    }

    TEST_RESULTS.append(result)
    return result


class TestTritonJITKernels:
    """Test Triton JIT kernels auto-generated by torch.inductor.

    These tests correspond to the 19 Triton kernels identified in S2V profiling.
    Tests use actual vllm-omni implementations that trigger kernel generation.

    Total Triton kernel overhead: ~453.30ms
    See TRITON_KERNEL_MAPPING.md for complete analysis.
    """

    def test_layer_norm_fused(self):
        """Test fused layer normalization (triton_red_fused__to_copy_native_layer_norm_0).

        Kernel: triton_red_fused__to_copy_native_layer_norm_0
        Performance: 16 calls, 18.76ms total (1.172ms/call)
        Operations: LayerNorm + dtype conversion (bf16 → fp32 → bf16)

        Source: norm1, norm2, norm3 in WanS2VTransformerBlock
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            layer_norm = torch.nn.LayerNorm(HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            return {"x": x}, layer_norm

        def compute(tensors, operation):
            # torch.compile will generate triton kernel for LayerNorm
            compiled_ln = torch.compile(operation, mode="max-autotune")
            return compiled_ln(tensors["x"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "LayerNorm Fused (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 18.76ms (1.172ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_gelu_activation(self):
        """Test GELU activation (triton_poi_fused_gelu_view_3).

        Kernel: triton_poi_fused_gelu_view_3
        Performance: 16 calls, 63.38ms total (3.961ms/call) ⚠️ MOST EXPENSIVE KERNEL
        Operations: GELU + view/reshape

        Source: WanFeedForward.forward() - FFN activation
        GELU: 0.5 * x * (1 + tanh(sqrt(2/π) * (x + 0.044715 * x³)))
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            # FFN intermediate dimension
            x = torch.randn(BATCH_SIZE, SEQ_LEN, FFN_DIM, device="cpu", dtype=torch.bfloat16)
            return {"x": x}, None

        def compute(tensors, operation):
            # torch.compile will generate triton kernel for GELU
            def gelu_fn(x):
                return torch.nn.functional.gelu(x)

            compiled_gelu = torch.compile(gelu_fn, mode="max-autotune")
            return compiled_gelu(tensors["x"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "ffn_dim": FFN_DIM}

        result = benchmark_with_metrics(
            "GELU Activation (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 63.38ms (3.961ms/call) - HOTSPOT",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_segment_modulation_fused(self):
        """Test segment-wise modulation (triton_poi_fused_add_cat_mul_slice_view_4).

        Kernel: triton_poi_fused_add_cat_mul_slice_view_4
        Performance: 16 calls, 48.50ms total (3.031ms/call) ⚠️ HIGH OVERHEAD
        Operations: add + cat + mul + slice + view (S2V segment modulation)

        Source: WanS2VTransformerBlock.forward() lines 445-448
        Splits tensor into segments, applies per-segment modulation, reassembles
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            # Two segments: noisy tokens + ref/motion tokens
            seg_idx = [0, SEQ_LEN // 2, SEQ_LEN]
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            scale = torch.randn(BATCH_SIZE, 2, 1, device="cpu", dtype=torch.bfloat16)  # 2 segments
            return {"x": x, "scale": scale, "seg_idx": seg_idx}, None

        def compute(tensors, operation):
            # S2V segment modulation pattern
            def segment_modulation(x, scale, seg_idx):
                # Split and modulate each segment
                parts = []
                for i in range(2):
                    segment = x[:, seg_idx[i] : seg_idx[i + 1]]
                    modulated = segment * scale[:, i : i + 1]
                    parts.append(modulated)
                # Concatenate back
                return torch.cat(parts, dim=1)

            compiled_mod = torch.compile(segment_modulation, mode="max-autotune")
            return compiled_mod(tensors["x"], tensors["scale"], tensors["seg_idx"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM, "segments": 2}

        result = benchmark_with_metrics(
            "Segment Modulation (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 48.50ms (3.031ms/call) - S2V specific",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_residual_layernorm_fused(self):
        """Test residual + LayerNorm (triton_red_fused__to_copy_add_native_layer_norm_0).

        Kernel: triton_red_fused__to_copy_add_native_layer_norm_0
        Performance: 16 calls, 26.97ms total (1.685ms/call)
        Operations: Residual add + LayerNorm + dtype conversion

        Source: Post-attention/FFN residuals in WanS2VTransformerBlock
        x = x + self.self_attn(...) then norm(x)
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            residual = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            layer_norm = torch.nn.LayerNorm(HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            return {"x": x, "residual": residual}, layer_norm

        def compute(tensors, operation):
            # Fused residual + LayerNorm
            def residual_layernorm(x, residual, ln):
                return ln(x + residual)

            compiled_rln = torch.compile(residual_layernorm, mode="max-autotune")
            return compiled_rln(tensors["x"], tensors["residual"], operation)

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Residual + LayerNorm (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 26.97ms (1.685ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_rmsnorm_fused(self):
        """Test RMSNorm (triton_red_fused__to_copy_div_mul_pow_sqrt_sum_view_0).

        Kernel: triton_red_fused__to_copy_div_mul_pow_sqrt_sum_view_0
        Performance: 16 calls, 24.86ms total (1.554ms/call)
        Operations: RMSNorm - x / sqrt(mean(x²) + eps)

        Source: DistributedRMSNorm for QK normalization
        norm_q, norm_k in WanS2VSelfAttention and WanS2VCrossAttention
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Use torch.nn.RMSNorm (simple implementation without distributed requirements)
            rmsnorm = torch.nn.RMSNorm(HIDDEN_DIM, eps=1e-6, dtype=torch.bfloat16)
            return {"x": x}, rmsnorm

        def compute(tensors, operation):
            # torch.compile will generate triton kernel for RMSNorm
            compiled_rms = torch.compile(operation.forward, mode="max-autotune")
            return compiled_rms(tensors["x"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "RMSNorm (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 24.86ms (1.554ms/call) - QK norm",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_tensor_concat_fused(self):
        """Test tensor concatenation (triton_poi_fused_cat_4).

        Kernel: triton_poi_fused_cat_4
        Performance: 16 calls, 29.46ms total (1.841ms/call)
        Operations: Concatenate tensors

        Source: Multiple locations in WanS2VTransformerBlock
        - Concatenating segments after modulation
        - Combining ref/motion/noisy latents
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            # Simulate segment concatenation
            seg1 = torch.randn(BATCH_SIZE, SEQ_LEN // 2, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            seg2 = torch.randn(BATCH_SIZE, SEQ_LEN // 2, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            return {"seg1": seg1, "seg2": seg2}, None

        def compute(tensors, operation):
            # torch.compile will generate triton kernel for cat
            def cat_fn(seg1, seg2):
                return torch.cat([seg1, seg2], dim=1)

            compiled_cat = torch.compile(cat_fn, mode="max-autotune")
            return compiled_cat(tensors["seg1"], tensors["seg2"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Tensor Concat (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 29.46ms (1.841ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_clone_contiguous(self):
        """Test tensor clone (triton_poi_fused_clone_0).

        Kernel: triton_poi_fused_clone_0
        Performance: 16 calls, 45.07ms total (2.817ms/call)
        Operations: Clone tensor (make contiguous copy)

        Source: Before in-place operations in transformer blocks
        """
        if DEVICE == "cpu":
            pytest.skip("Triton kernels require XPU")

        def prepare():
            # Non-contiguous tensor (e.g., after transpose)
            x = torch.randn(BATCH_SIZE, HIDDEN_DIM, SEQ_LEN, device="cpu", dtype=torch.bfloat16)
            x = x.transpose(1, 2)  # Make non-contiguous
            return {"x": x}, None

        def compute(tensors, operation):
            # torch.compile will generate triton kernel for clone
            def clone_fn(x):
                return x.clone()

            compiled_clone = torch.compile(clone_fn, mode="max-autotune")
            return compiled_clone(tensors["x"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Tensor Clone (Triton)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Triton: 16 calls, 45.07ms (2.817ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )


class TestCompiledFxGraphOps:
    """Test CompiledFxGraph operations identified in S2V profiling.

    CompiledFxGraphs are FX graph representations generated by torch.compile.
    They contain optimized Triton kernels and ATen operations.

    Source analysis: COMPILED_FX_GRAPH_MAPPING.md
    Profiling: profiler_output_s2v_reduced1_flashattn_720p_stack/
               20260512-203940_stage_0_rep_0_diffusion_1778618380/trace_rank0.json.gz

    Total CompiledFxGraph overhead: ~137.18ms for 8 diffusion blocks
    """

    def test_cross_attention_qkv_projection(self):
        """Test cross-attention Q/K/V projection with QK normalization.

        CompiledFxGraph: Multiple graphs for linear operations
        Performance: Part of f3pgglmvuq7zbizm64mazsn2z7zzmeu77of6lrwovxuv7hnx7vrt
                    8 calls, ~22.142ms total (2.768ms/call)

        Source: wan2_2_s2v_transformer.py:372-377 (WanS2VCrossAttention.forward)
        ```python
        b, n, d = x.size(0), self.num_heads, self.head_dim

        q = self.norm_q(self.to_q(x)).view(b, -1, n, d)
        k = self.norm_k(self.to_k(context)).view(b, -1, n, d)
        v = self.to_v(context).view(b, -1, n, d)
        ```

        Operations compiled:
        - Linear projections (to_q, to_k, to_v)
        - RMSNorm for query and key
        - Reshape to multi-head format
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            context = torch.randn(BATCH_SIZE, 512, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)

            # Simulate cross-attention QKV projection + QK norm (lines 372-377)
            # Using basic torch.nn modules instead of full WanS2VCrossAttention
            # to avoid tensor parallel initialization requirements
            class SimpleCrossAttnQKV(torch.nn.Module):
                def __init__(self):
                    super().__init__()
                    self.to_q = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)
                    self.to_k = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)
                    self.to_v = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)
                    self.norm_q = torch.nn.LayerNorm(HIDDEN_DIM, dtype=torch.bfloat16)
                    self.norm_k = torch.nn.LayerNorm(HIDDEN_DIM, dtype=torch.bfloat16)

                def forward(self, x, context):
                    b = x.size(0)
                    q = self.to_q(x)
                    q = self.norm_q(q).view(b, -1, NUM_HEADS, HEAD_DIM)
                    k = self.to_k(context)
                    k = self.norm_k(k).view(b, -1, NUM_HEADS, HEAD_DIM)
                    v = self.to_v(context).view(b, -1, NUM_HEADS, HEAD_DIM)
                    return q, k, v

            cross_attn_qkv = SimpleCrossAttnQKV()

            return {"x": x, "context": context}, cross_attn_qkv

        def compute(tensors, operation):
            compiled_forward = torch.compile(operation.forward, mode="max-autotune")
            return compiled_forward(tensors["x"], tensors["context"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "context_len": 512, "hidden_dim": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Cross-Attn QKV Projection (CompiledFxGraph)",
            prepare,
            compute,
            "matmul",
            shape_info,
            profiling_info="Graph f3pg...: 8 calls, 22.142ms (2.768ms/call) - includes QK norm",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_cross_attention_sdpa_call(self):
        """Test cross-attention SDPA kernel dispatch.

        CompiledFxGraph: Graph containing attention computation
        Performance: Part of f4w2zkx6c53q3cljuq46ts6s7p3brihdmdrmzqp66gt5d44244xd
                    8 calls, ~4.621ms total (0.578ms/call)

        Source: wan2_2_s2v_transformer.py:378 (WanS2VCrossAttention.forward)
        ```python
        with torch.profiler.record_function(f"CrossAttn_SDPA qkv_shapes={list(q.shape)}_{list(k.shape)}"):
            x = self.attn(q, k, v)
        ```

        Operations compiled:
        - Flash Attention varlen_fwd call
        - Tensor reshaping for SDPA format
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Pre-projected and reshaped Q/K/V (need [B, N, S, D] format for SDPA)
            q = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            k = torch.randn(BATCH_SIZE, 512, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            v = torch.randn(BATCH_SIZE, 512, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)

            return {"q": q, "k": k, "v": v}, None

        def compute(tensors, operation):
            # torch.compile will generate CompiledFxGraph for scaled_dot_product_attention
            def attn_fn(q, k, v):
                # Transpose to [B, N, S, D] format for scaled_dot_product_attention
                q_t = q.transpose(1, 2)
                k_t = k.transpose(1, 2)
                v_t = v.transpose(1, 2)
                out = torch.nn.functional.scaled_dot_product_attention(
                    q_t, k_t, v_t, attn_mask=None, dropout_p=0.0, is_causal=False, scale=1.0 / (HEAD_DIM**0.5)
                )
                # Transpose back to [B, S, N, D]
                return out.transpose(1, 2)

            compiled_attn = torch.compile(attn_fn, mode="max-autotune")
            return compiled_attn(tensors["q"], tensors["k"], tensors["v"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "kv_len": 512, "num_heads": NUM_HEADS}

        result = benchmark_with_metrics(
            "Cross-Attn SDPA Call (CompiledFxGraph)",
            prepare,
            compute,
            "attention",
            shape_info,
            profiling_info="Graph f4w2...: 8 calls, 4.621ms (0.578ms/call) - flash_attn dispatch",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_cross_attention_output_projection(self):
        """Test cross-attention output projection and dtype conversion.

        CompiledFxGraph: Graph for output linear layer
        Performance: Part of fuxoqq636fw6coejspxsqj6xoukduqwr2x5pyr6fcnsbfjw7nlz4
                    8 calls, ~8.098ms total (1.012ms/call)

        Source: wan2_2_s2v_transformer.py:380-383 (WanS2VCrossAttention.forward)
        ```python
        x = x.flatten(2, 3)
        x = x.type_as(q)

        x = self.to_out(x)
        ```

        Operations compiled:
        - Flatten multi-head dimension
        - Dtype conversion (type_as)
        - Linear output projection
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Attention output (multi-head format)
            attn_out = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            # Reference for dtype
            q_ref = torch.randn(BATCH_SIZE, 1, 1, 1, device="cpu", dtype=torch.bfloat16)

            # Create output projection
            out_proj = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)

            return {"attn_out": attn_out, "q_ref": q_ref}, out_proj

        def compute(tensors, operation):
            # torch.compile will fuse flatten + type_as + linear
            def out_proj_fn(attn_out, q_ref):
                x = attn_out.flatten(2, 3)
                x = x.type_as(q_ref)
                return operation(x)

            compiled_out = torch.compile(out_proj_fn, mode="max-autotune")
            return compiled_out(tensors["attn_out"], tensors["q_ref"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "in_features": HIDDEN_DIM, "out_features": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Cross-Attn Output Proj (CompiledFxGraph)",
            prepare,
            compute,
            "matmul",
            shape_info,
            profiling_info="Graph fuxo...: 8 calls, 8.098ms (1.012ms/call) - flatten + linear",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_segment_modulation_pre_attention(self):
        """Test segment-wise modulation before self-attention.

        CompiledFxGraph: fl3b4s7sfb5g5ropiiyt37evy2xte2hylfysmmnwyr2otlxedhsm
        Performance: 8 calls, 59.601ms total (7.450ms/call) ⚠️ MOST EXPENSIVE

        Source: wan2_2_s2v_transformer.py:437-442 (WanS2VTransformerBlock.forward)
        ```python
        # Per-segment modulation
        norm_x = self.norm1(x).type_as(x)
        parts = []
        for i in range(2):
            parts.append(norm_x[:, seg_idx[i]:seg_idx[i+1]] * (1 + e[1][:, i:i+1]) + e[0][:, i:i+1])
        norm_x = torch.cat(parts, dim=1)
        ```

        Operations compiled:
        - LayerNorm (triton_red_fused__to_copy_native_layer_norm_0)
        - Segment slicing and modulation (triton_poi_fused_*_2)
        - Tensor concatenation
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Input latent features
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Modulation parameters (shift, scale) for 2 segments
            e_shift = torch.randn(BATCH_SIZE, 2, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            e_scale = torch.randn(BATCH_SIZE, 2, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Segment boundaries (noisy vs ref/motion)
            seg_idx = [0, SEQ_LEN // 2, SEQ_LEN]

            # Create LayerNorm
            norm = torch.nn.LayerNorm(HIDDEN_DIM, dtype=torch.bfloat16)

            return {"x": x, "e_shift": e_shift, "e_scale": e_scale, "seg_idx": seg_idx}, norm

        def compute(tensors, operation):
            # torch.compile will fuse norm + segment modulation + cat
            def segment_mod_fn(x, e_shift, e_scale, seg_idx):
                norm_x = operation(x).type_as(x)
                parts = []
                for i in range(2):
                    part = norm_x[:, seg_idx[i] : seg_idx[i + 1]]
                    part = part * (1 + e_scale[:, i : i + 1]) + e_shift[:, i : i + 1]
                    parts.append(part)
                return torch.cat(parts, dim=1)

            compiled_mod = torch.compile(segment_mod_fn, mode="max-autotune")
            return compiled_mod(tensors["x"], tensors["e_shift"], tensors["e_scale"], tensors["seg_idx"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM, "num_segments": 2}

        result = benchmark_with_metrics(
            "Segment Modulation Pre-Attn (CompiledFxGraph)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Graph fl3b...: 8 calls, 59.601ms (7.450ms/call) - HOTSPOT",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_segment_reassembly_post_attention(self):
        """Test segment-wise scaling and reassembly after self-attention.

        CompiledFxGraph: f32lhthuanz4znxl7p2g7ykcrlct4l6dscn7pmsboyke56pepsgh
        Performance: 8 calls, 16.582ms total (2.073ms/call)

        Source: wan2_2_s2v_transformer.py:445-448 (WanS2VTransformerBlock.forward)
        ```python
        # Apply segment-wise scale after attention
        y_parts = []
        for i in range(2):
            y_parts.append(y[:, seg_idx[i]:seg_idx[i+1]] * e[2][:, i:i+1])
        x = x + torch.cat(y_parts, dim=1)
        ```

        Operations compiled:
        - Segment slicing (triton_poi_fused_mul_slice_0/1)
        - Element-wise multiplication with gate
        - Residual connection + LayerNorm (triton_red_fused__to_copy_add_cat_native_layer_norm_2)
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Original input
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Attention output
            y = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Gate parameters for 2 segments
            e_gate = torch.randn(BATCH_SIZE, 2, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            # Segment boundaries
            seg_idx = [0, SEQ_LEN // 2, SEQ_LEN]

            return {"x": x, "y": y, "e_gate": e_gate, "seg_idx": seg_idx}, None

        def compute(tensors, operation):
            # torch.compile will fuse segment scale + cat + residual
            def segment_reassembly_fn(x, y, e_gate, seg_idx):
                y_parts = []
                for i in range(2):
                    part = y[:, seg_idx[i] : seg_idx[i + 1]]
                    part = part * e_gate[:, i : i + 1]
                    y_parts.append(part)
                return x + torch.cat(y_parts, dim=1)

            compiled_reassembly = torch.compile(segment_reassembly_fn, mode="max-autotune")
            return compiled_reassembly(tensors["x"], tensors["y"], tensors["e_gate"], tensors["seg_idx"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM, "num_segments": 2}

        result = benchmark_with_metrics(
            "Segment Reassembly Post-Attn (CompiledFxGraph)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Graph f32l...: 8 calls, 16.582ms (2.073ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_ffn_linear_layers(self):
        """Test FFN upproject and downproject linear layers.

        CompiledFxGraph: f3pgglmvuq7zbizm64mazsn2z7zzmeu77of6lrwovxuv7hnx7vrt
        Performance: 8 calls, ~22.142ms total (2.768ms/call)

        Source: Multiple locations in WanFeedForward
        - Upproject: fc1 (5120 -> 13824)
        - Downproject: fc2 (13824 -> 5120)

        Operations compiled:
        - Matrix multiplication (aten::addmm)
        - Bias addition
        - Tensor reshaping (aten::as_strided)
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)

            # Simulate FFN without distributed layers
            class SimpleFFN(torch.nn.Module):
                def __init__(self):
                    super().__init__()
                    self.fc1 = torch.nn.Linear(HIDDEN_DIM, FFN_DIM, bias=True, dtype=torch.bfloat16)
                    self.fc2 = torch.nn.Linear(FFN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)

                def forward(self, x):
                    x = self.fc1(x)
                    x = torch.nn.functional.gelu(x)
                    x = self.fc2(x)
                    return x

            ffn = SimpleFFN()

            return {"x": x}, ffn

        def compute(tensors, operation):
            compiled_ffn = torch.compile(operation.forward, mode="max-autotune")
            return compiled_ffn(tensors["x"])

        shape_info = {
            "batch": BATCH_SIZE,
            "seq_len": SEQ_LEN,
            "in_features": HIDDEN_DIM,
            "hidden_features": FFN_DIM,
        }

        result = benchmark_with_metrics(
            "FFN Linear Layers (CompiledFxGraph)",
            prepare,
            compute,
            "matmul",
            shape_info,
            profiling_info="Graph f3pg...: 8 calls, 22.142ms (2.768ms/call) - fc1 + gelu + fc2",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_cumsum_seqlen_generation(self):
        """Test cumulative sequence length generation for flash attention.

        CompiledFxGraph: fvp5nk3lebqiampquz37p7byzynkdu7hnmljuxevxjlf2e523tuy
        Performance: 8 calls, 2.783ms total (0.348ms/call)

        Source: flash_attn.py:126-127 (FlashAttentionBackend._forward_varlen_dense)
        ```python
        cu_seqlens_q = torch.arange(0, (batch_size + 1) * q_len, step=q_len, ...)
        cu_seqlens_k = torch.arange(0, (batch_size + 1) * k_len, step=k_len, ...)
        ```

        Operations compiled:
        - Range generation (triton_poi_fused_arange_0)
        - Tensor allocation (aten::empty)
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            batch_size = BATCH_SIZE
            q_len = SEQ_LEN
            k_len = 512

            return {"batch_size": batch_size, "q_len": q_len, "k_len": k_len}, None

        def compute(tensors, operation):
            # torch.compile will optimize arange generation
            def cumsum_fn(batch_size, q_len, k_len):
                cu_seqlens_q = torch.arange(0, (batch_size + 1) * q_len, step=q_len, dtype=torch.int32, device=DEVICE)
                cu_seqlens_k = torch.arange(0, (batch_size + 1) * k_len, step=k_len, dtype=torch.int32, device=DEVICE)
                return cu_seqlens_q, cu_seqlens_k

            compiled_cumsum = torch.compile(cumsum_fn, mode="max-autotune")
            return compiled_cumsum(tensors["batch_size"], tensors["q_len"], tensors["k_len"])

        shape_info = {"batch": BATCH_SIZE, "q_len": SEQ_LEN, "k_len": 512}

        result = benchmark_with_metrics(
            "Cumsum SeqLen Generation (CompiledFxGraph)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Graph fvp5...: 8 calls, 2.783ms (0.348ms/call)",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_self_attention_qkv_projection_and_norm(self):
        """Test self-attention QKV projection with QK normalization.

        CompiledFxGraph: Multiple graphs for fused QKV + split + norm operations
        Performance: Part of larger self-attention graph (~10ms per block)

        Source: wan2_2_s2v_transformer.py:298-306 (WanS2VSelfAttention.forward)
        ```python
        # Fused QKV
        qkv, _ = self.to_qkv(x)
        q_size = self.num_heads * self.head_dim
        kv_size = self.num_kv_heads * self.head_dim
        query, key, value = qkv.split([q_size, kv_size, kv_size], dim=-1)

        # QK normalization
        query = self.norm_q(query)
        key = self.norm_k(key)
        ```

        Operations compiled:
        - ColumnParallelLinear for fused QKV projection (5120 → 15360)
        - Tensor split into Q/K/V
        - RMSNorm for query and key
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            x = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)

            # Simulate self-attention QKV projection + split + QK norm (lines 298-306)
            # Using basic torch.nn modules to avoid tensor parallel requirements
            class SimpleSelfAttnQKV(torch.nn.Module):
                def __init__(self):
                    super().__init__()
                    self.qkv_proj = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM * 3, bias=True, dtype=torch.bfloat16)
                    self.norm_q = torch.nn.RMSNorm(HIDDEN_DIM, dtype=torch.bfloat16)
                    self.norm_k = torch.nn.RMSNorm(HIDDEN_DIM, dtype=torch.bfloat16)

                def forward(self, x):
                    qkv = self.qkv_proj(x)
                    q_size = HIDDEN_DIM
                    query, key, value = qkv.split([q_size, q_size, q_size], dim=-1)
                    query = self.norm_q(query)
                    key = self.norm_k(key)
                    return query, key, value

            self_attn_qkv = SimpleSelfAttnQKV()

            return {"x": x}, self_attn_qkv

        def compute(tensors, operation):
            compiled_qkv = torch.compile(operation.forward, mode="max-autotune")
            return compiled_qkv(tensors["x"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "hidden_dim": HIDDEN_DIM, "qkv_dim": HIDDEN_DIM * 3}

        result = benchmark_with_metrics(
            "Self-Attn QKV Proj+Norm (CompiledFxGraph)",
            prepare,
            compute,
            "matmul",
            shape_info,
            profiling_info="Lines 298-306: QKV proj + split + QK norm",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_self_attention_qkv_reshape(self):
        """Test self-attention QKV reshape to multi-head format.

        CompiledFxGraph: f47nghfsr6cryiu4bcmtzexaprlxlogytrdej2ydygprd664ltxa
        Performance: 8 calls, 5.242ms total (0.655ms/call)

        Source: wan2_2_s2v_transformer.py:308-311 (WanS2VSelfAttention.forward)
        ```python
        # Reshape to [B, S, N, D]
        query = query.view(b, s, self.num_heads, self.head_dim)
        key = key.view(b, s, self.num_kv_heads, self.head_dim)
        value = value.view(b, s, self.num_kv_heads, self.head_dim)
        ```

        Operations compiled:
        - Tensor view/reshape (aten::view)
        - Memory layout optimization (aten::as_strided)
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Flat QKV after split and norm
            query = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            key = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)
            value = torch.randn(BATCH_SIZE, SEQ_LEN, HIDDEN_DIM, device="cpu", dtype=torch.bfloat16)

            return {"query": query, "key": key, "value": value}, None

        def compute(tensors, operation):
            # torch.compile will optimize view operations
            def reshape_fn(query, key, value):
                b, s = query.shape[:2]
                query = query.view(b, s, NUM_HEADS, HEAD_DIM)
                key = key.view(b, s, NUM_HEADS, HEAD_DIM)
                value = value.view(b, s, NUM_HEADS, HEAD_DIM)
                return query, key, value

            compiled_reshape = torch.compile(reshape_fn, mode="max-autotune")
            return compiled_reshape(tensors["query"], tensors["key"], tensors["value"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "num_heads": NUM_HEADS, "head_dim": HEAD_DIM}

        result = benchmark_with_metrics(
            "Self-Attn QKV Reshape (CompiledFxGraph)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Graph f47n...: 8 calls, 5.242ms (0.655ms/call) - lines 308-311",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_self_attention_rope_application(self):
        """Test RoPE application to Q/K in self-attention.

        CompiledFxGraph: f666awkfmjimizysydzi26g2vvvqxhh3fhiyg7m6yb2tu6jc77of
        Performance: 8 calls, 6.895ms total (0.862ms/call)

        Source: wan2_2_s2v_transformer.py:313-315 (WanS2VSelfAttention.forward)
        ```python
        # Apply S2V complex-valued RoPE
        query = rope_apply_s2v(query, grid_sizes, freqs)
        key = rope_apply_s2v(key, grid_sizes, freqs)
        ```

        Operations compiled:
        - Complex-valued rotation (torch.view_as_complex)
        - BF16→FP32→BF16 conversions
        - Element-wise complex multiplication
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            query = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            key = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            # Grid sizes: [T, H, W] = [21, 45, 80] for 720p
            grid_sizes = torch.tensor([[21, 45, 80]], dtype=torch.int32, device="cpu")
            # Precomputed frequencies - shape [B, S, n, HEAD_DIM//2] complex
            # rope_apply_s2v expects freqs[i, :s, :n] which broadcasts with x_i [s, n, HEAD_DIM//2]
            freqs = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM // 2, device="cpu", dtype=torch.complex64)

            # Import actual rope_apply_s2v
            from vllm_omni.diffusion.models.wan2_2.wan2_2_s2v_transformer import rope_apply_s2v

            return {"query": query, "key": key, "grid_sizes": grid_sizes, "freqs": freqs}, rope_apply_s2v

        def compute(tensors, operation):
            # torch.compile will optimize RoPE operations
            def rope_fn(query, key, grid_sizes, freqs):
                query = operation(query, grid_sizes, freqs)
                key = operation(key, grid_sizes, freqs)
                return query, key

            compiled_rope = torch.compile(rope_fn, mode="max-autotune")
            return compiled_rope(tensors["query"], tensors["key"], tensors["grid_sizes"], tensors["freqs"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "num_heads": NUM_HEADS, "head_dim": HEAD_DIM}

        result = benchmark_with_metrics(
            "Self-Attn RoPE Apply (CompiledFxGraph)",
            prepare,
            compute,
            "elementwise",
            shape_info,
            profiling_info="Graph f666...: 8 calls, 6.895ms (0.862ms/call) - lines 313-315",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_self_attention_sdpa_call(self):
        """Test self-attention SDPA kernel dispatch.

        CompiledFxGraph: Graph containing self-attention computation
        Performance: Part of f4w2zkx6c53q3cljuq46ts6s7p3brihdmdrmzqp66gt5d44244xd
                    8 calls, ~4.621ms total (0.578ms/call)

        Source: wan2_2_s2v_transformer.py:323-324 (WanS2VSelfAttention.forward)
        ```python
        with torch.profiler.record_function(f"SelfAttn_SDPA qkv_shapes={list(query.shape)}"):
            hidden_states = self.attn(query, key, value)
        ```

        Operations compiled:
        - Flash Attention varlen_fwd call (self-attention)
        - Tensor reshaping for SDPA format
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Pre-projected and reshaped Q/K/V after RoPE (self-attention)
            query = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            key = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            value = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)

            return {"query": query, "key": key, "value": value}, None

        def compute(tensors, operation):
            # torch.compile will generate CompiledFxGraph for scaled_dot_product_attention
            def attn_fn(query, key, value):
                # Transpose to [B, N, S, D] format for scaled_dot_product_attention
                q_t = query.transpose(1, 2)
                k_t = key.transpose(1, 2)
                v_t = value.transpose(1, 2)
                out = torch.nn.functional.scaled_dot_product_attention(
                    q_t, k_t, v_t, attn_mask=None, dropout_p=0.0, is_causal=False, scale=1.0 / (HEAD_DIM**0.5)
                )
                # Transpose back to [B, S, N, D]
                return out.transpose(1, 2)

            compiled_attn = torch.compile(attn_fn, mode="max-autotune")
            return compiled_attn(tensors["query"], tensors["key"], tensors["value"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "num_heads": NUM_HEADS, "head_dim": HEAD_DIM}

        result = benchmark_with_metrics(
            "Self-Attn SDPA Call (CompiledFxGraph)",
            prepare,
            compute,
            "attention",
            shape_info,
            profiling_info="Graph f4w2...: 8 calls, 4.621ms (0.578ms/call) - lines 323-324",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )

    def test_self_attention_output_flatten_proj(self):
        """Test self-attention output flatten and projection.

        CompiledFxGraph: fuxoqq636fw6coejspxsqj6xoukduqwr2x5pyr6fcnsbfjw7nlz4
        Performance: 8 calls, ~8.098ms total (1.012ms/call)

        Source: wan2_2_s2v_transformer.py:325-329 (WanS2VSelfAttention.forward)
        ```python
        hidden_states = hidden_states.flatten(2, 3)
        hidden_states = hidden_states.type_as(x)

        # Output
        hidden_states = self.to_out(hidden_states)
        ```

        Operations compiled:
        - Flatten multi-head dimension
        - Dtype conversion
        - Output linear projection
        """
        if DEVICE == "cpu":
            pytest.skip("CompiledFxGraph requires XPU")

        def prepare():
            # Attention output (multi-head format)
            attn_out = torch.randn(BATCH_SIZE, SEQ_LEN, NUM_HEADS, HEAD_DIM, device="cpu", dtype=torch.bfloat16)
            # Reference for dtype
            x_ref = torch.randn(BATCH_SIZE, 1, 1, device="cpu", dtype=torch.bfloat16)

            # Create output projection
            out_proj = torch.nn.Linear(HIDDEN_DIM, HIDDEN_DIM, bias=True, dtype=torch.bfloat16)

            return {"attn_out": attn_out, "x_ref": x_ref}, out_proj

        def compute(tensors, operation):
            # torch.compile will fuse flatten + type_as + linear
            def out_proj_fn(attn_out, x_ref):
                hidden_states = attn_out.flatten(2, 3)
                hidden_states = hidden_states.type_as(x_ref)
                return operation(hidden_states)

            compiled_out = torch.compile(out_proj_fn, mode="max-autotune")
            return compiled_out(tensors["attn_out"], tensors["x_ref"])

        shape_info = {"batch": BATCH_SIZE, "seq_len": SEQ_LEN, "in_features": HIDDEN_DIM, "out_features": HIDDEN_DIM}

        result = benchmark_with_metrics(
            "Self-Attn Output Proj (CompiledFxGraph)",
            prepare,
            compute,
            "matmul",
            shape_info,
            profiling_info="Graph fuxo...: 8 calls, 8.098ms (1.012ms/call) - lines 325-329",
        )

        if result:
            print(
                f"\n{result['name']}: {result['avg_ms']:.3f}ms, "
                f"{result['tflops']:.2f} TFLOPs, {result['memory_bw_gbs']:.2f} GB/s"
            )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
